### ISSUE TITLE
Text not showing in certain pdfs on Windows machines

### ISSUE THREAD

**Issue by ArakliotisStelios** [wojtekmaj/react-pdf#1024]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Text is not showing on certain pdfs. I tried all the versions, even the beta. Also tried to import fonts, cmaps etc. 
Also tried different render methods canvas/svg.
It seems that even on [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html) is not showing correctly. 
The strange thing is that on Mac machines it works great but it fails only in Window machines.
Here is a live code [example](https://codesandbox.io/s/pensive-rubin-rt89yt?file=/src/App.js). 

### Steps to reproduce

Go to https://codesandbox.io/s/pensive-rubin-rt89yt?file=/src/App.js and open it on a **Windows** machine 

### Expected behavior

The expected behavior is to show text

### Actual behavior

The actual behavior is not showing the text.

### Environment

- **Machine**: Only on Windows
- **Browser (if applicable)**:any
- **React-PDF version**:any
- **React version**:any
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Should be resolved in v6.0.0. May try and backport that to 5.x if there's demand.

**Comment by nejcjelovcan** [comment]
The issue persists on Windows machines (tried with Edge 111, Firefox 111, Chrome 111, Opera 97). Tested with react-pdf 6.2.2, pdfjs 2.16.105.

Example: https://codesandbox.io/s/angry-rui-nxdz5g
