### ISSUE TITLE
"Rendering cancelled, page .." error after upgrade from 2.1.0 to 2.4.2

### ISSUE THREAD

**Issue by ramusus** [wojtekmaj/react-pdf#122]
I start getting this error when I switch from rendering one pdf to another. Perhaps, I need to stop rendering somehow in `componentWillUnmount`?

**Comment by ramusus** [comment]
Doing the same and using version 2.1.0 I'm getting this error:
```
Error while loading page! Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.
```
Perhaps it's the same issue

**Comment by wojtekmaj** [comment]
Yeah, indeed that's the same thing. Only in version 2.1.0 rendering a new page/PDF before previous render has finised wasn't handled very well. Currently, we do exactly what you wanted to do: we stop rendering in `componentWillUnmount` before we start another one.

It is entirely safe and expected.

If you have any additional questions, I'm happy to reopen!

**Comment by ramusus** [comment]
The problem is with version 2.4.2 I got error "Rendering cancelled, page .." I don't see it stops rendering internally. That's why I open this issue with question 

> do I need to stop rendering somehow in componentWillUnmount?

**Comment by wojtekmaj** [comment]
Hmmm. We're definitely calling cancel() and that message `Rendering cancelled...` comes from PDF.js internally and may be treated as a confirmation everything is okay on our side. If that doesn't stop rendering (frankly, I don't even know how to reliably check that) then we have a problem with Mozilla's PDF.js.

**Comment by ramusus** [comment]
Confirm 2.4.2 raise error with stack trace:
```
Rendering cancelled, page 4 RenderingCancelledException {message: "Rendering cancelled, page 4", type: "canvas"}
consoleOnDev @ util.js:152
errorOnDev @ util.js:169
PageCanvas._this.onRenderError @ PageCanvas.js:64
Promise rejected (async)
PageCanvas._this.drawPageOnCanvas @ PageCanvas.js:100
commitAttachRef @ react-dom.development.js:8864
commitAllLifeCycles @ react-dom.development.js:9972
callCallback @ react-dom.development.js:540
invokeGuardedCallbackDev @ react-dom.development.js:579
invokeGuardedCallback @ react-dom.development.js:436
commitRoot @ react-dom.development.js:10071
performWorkOnRoot @ react-dom.development.js:11003
performWork @ react-dom.development.js:10952
requestWork @ react-dom.development.js:10861
scheduleWorkImpl @ react-dom.development.js:10744
scheduleWork @ react-dom.development.js:10706
enqueueSetState @ react-dom.development.js:6204
Component.setState @ react.development.js:226
Page._this.onLoadSuccess @ Page.js:84
Promise resolved (async)
loadPage @ Page.js:187
componentDidMount @ Page.js:109
commitLifeCycles @ react-dom.development.js:8798
commitAllLifeCycles @ react-dom.development.js:9967
callCallback @ react-dom.development.js:540
invokeGuardedCallbackDev @ react-dom.development.js:579
invokeGuardedCallback @ react-dom.development.js:436
commitRoot @ react-dom.development.js:10071
performWorkOnRoot @ react-dom.development.js:11003
performWork @ react-dom.development.js:10952
requestWork @ react-dom.development.js:10861
scheduleWorkImpl @ react-dom.development.js:10744
scheduleWork @ react-dom.development.js:10706
enqueueSetState @ react-dom.development.js:6204
Component.setState @ react.development.js:226
Document._this.onLoadSuccess @ Document.js:139
Promise resolved (async)
Document._this.onSourceSuccess @ Document.js:123
Promise resolved (async)
loadDocument @ Document.js:303
componentWillReceiveProps @ Document.js:242
callComponentWillReceiveProps @ react-dom.development.js:6372
updateClassInstance @ react-dom.development.js:6553
updateClassComponent @ react-dom.development.js:7877
beginWork @ react-dom.development.js:8253
performUnitOfWork @ react-dom.development.js:10244
workLoop @ react-dom.development.js:10308
callCallback @ react-dom.development.js:540
invokeGuardedCallbackDev @ react-dom.development.js:579
invokeGuardedCallback @ react-dom.development.js:436
renderRoot @ react-dom.development.js:10386
performWorkOnRoot @ react-dom.development.js:11000
performWork @ react-dom.development.js:10952
requestWork @ react-dom.development.js:10861
scheduleWorkImpl @ react-dom.development.js:10744
scheduleWork @ react-dom.development.js:10706
enqueueSetState @ react-dom.development.js:6204
Component.setState @ react.development.js:226
UploadStep._this.openNextPreview @ UploadStep.jsx:169
callback @ HotKeys.js:161
_fireCallback @ mousetrap.js:616
Mousetrap.self._handleKey @ mousetrap.js:677
Mousetrap.handleKey @ mousetrap.js:994
_handleKeyEvent @ mousetrap.js:737
```

**Comment by wojtekmaj** [comment]
Thanks so much. Figured this out. 3 months ago there was a major change in PDF.js API which changed the errors thrown on render cancel. This caused React-PDF to stop filtering them out (they SHOULD be ignored).
I'll fix this in the coming release!

**Comment by wojtekmaj** [comment]
The issue should be fixed in 2.5.2.

**Comment by wakasabbasid** [comment]
@wojtekmaj This issue is still occurring on "react-pdf": "^5.2.0"
