### ISSUE TITLE
PDFjs-dist error

### ISSUE THREAD

**Issue by nike1v** [wojtekmaj/react-pdf#1822]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I had used previous version of your library and though of using it as base for my needs since it doesn't cover all points that is required by my tasks. But since the update to 9.0.0 i do have this issue whenever I try to import anything from your library of pdfjs-dist. I know that this is not particularly your issue, but maybe you do know the solution for this.
![image](https://github.com/wojtekmaj/react-pdf/assets/20584538/a5a89bd2-efb0-4b77-a4db-12a9c2cad01d)

### Steps to reproduce

import anything from react-pdf or pdfjs-dist

### Expected behavior

component loads without errors

### Actual behavior

When pdfjs-dist is imported from react-pdf (or components that use pdfjs-dist) or even the pdfjs-dist is imported, the error occures:
![image](https://github.com/wojtekmaj/react-pdf/assets/20584538/db75ce6e-8ba4-4c3c-9340-4389aed86d41)

### Environment

- **Browser (if applicable)**: Chorme latest, Arc Windows latest
- **React-PDF version**: 9.0.0 (pdfjs-dist 4.3.136)
- **React version**: 18.3.1
- **Webpack version (if applicable)**: nextjs 14.2.3

**Comment by wojtekmaj** [comment]
What do you set workerSrc to?

**Comment by nike1v** [comment]
I have tried the way with `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs` and the recomended by you new URL...

**Comment by nike1v** [comment]
The problem is TurboPack in my case, since without turbo it works as it should.

**Comment by nike1v** [comment]
Also I do have some functional that I need to use, so I have some questions:
Does your library is capable of working with forms? Extracting, prefilling with data.
Does your library can work with Toolbar (pages, scale, search, document properties)?
Does your library have flag for forms that will bake them READ-ONLY and block all fields?
If no, I would like to contribute or I will have to do it myself.
Thanks in advance!

**Comment by DonikaV** [comment]
+1

```
import { Document, Page, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.mjs',
  import.meta.url,
).toString();
```

Module not found: Can't resolve 'pdfjs-dist/build/pdf.worker.min.mjs'

**Comment by nike1v** [comment]
> +1 in version 9.00, before was working fine
> 
> ```
> import { Document, Page, pdfjs } from 'react-pdf';
> pdfjs.GlobalWorkerOptions.workerSrc = new URL(
>   'pdfjs-dist/build/pdf.worker.min.mjs',
>   import.meta.url,
> ).toString();
> ```
> 
> Module not found: Can't resolve 'pdfjs-dist/build/pdf.worker.min.mjs'

Have you tried dev mode without TurboPack?

**Comment by DonikaV** [comment]
> > +1 in version 9.00, before was working fine
> > ```
> > import { Document, Page, pdfjs } from 'react-pdf';
> > pdfjs.GlobalWorkerOptions.workerSrc = new URL(
> >   'pdfjs-dist/build/pdf.worker.min.mjs',
> >   import.meta.url,
> > ).toString();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Module not found: Can't resolve 'pdfjs-dist/build/pdf.worker.min.mjs'
> 
> Have you tried dev mode without TurboPack?

I am not using turbopack

**Comment by DonikaV** [comment]
Downgraded to the 8.02 and now have this
{
    "message": "The API version \"4.3.136\" does not match the Worker version \"3.11.174\".",
    "name": "UnknownErrorException",
    "details": "Error: The API version \"4.3.136\" does not match the Worker version \"3.11.174\"."
}
Maybe some cache...

**Comment by nike1v** [comment]
> Ok, so remove node_modules clean yarn.lock file yarn install Works with 9.0.0, but before I did the same and didn't worked. I don't know ...

As you said, probably some cache issues, glad it worked.

**Comment by DonikaV** [comment]
> > Ok, so remove node_modules clean yarn.lock file yarn install Works with 9.0.0, but before I did the same and didn't worked. I don't know ...
> 
> As you said, probably some cache issues, glad it worked.

The build failing in GitHub Action
  Creating an optimized production build ...
Failed to compile.

static/media/pdf.worker.min.9b170941.mjs from Terser
  x 'import', and 'export' cannot be used outside of module code
    ,-[18:1]
 18 |  *
 19 |  * @licend The above is the entire license notice for the
 20 |  * JavaScript code in this page

**Comment by nike1v** [comment]
> > > Ok, so remove node_modules clean yarn.lock file yarn install Works with 9.0.0, but before I did the same and didn't worked. I don't know ...
> > 
> > 
> > As you said, probably some cache issues, glad it worked.
> 
> The build failing in GitHub Action and locally now, but next dev works Creating an optimized production build ... Failed to compile.
> 
> ```
> static/media/pdf.worker.min.9b170941.mjs from Terser
>   x 'import', and 'export' cannot be used outside of module code
>     ,-[18:1]
>  18 |  *
>  19 |  * @licend The above is the entire license notice for the
>  20 |  * JavaScript code in this page
> ```
> 
> <img alt="image" width="1495" src="https://private-user-images.githubusercontent.com/26111842/337344049-ecc7fe74-8224-487e-9673-2a66cba8c96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTA1NDQsIm5iZiI6MTcxNzY5MDI0NCwicGF0aCI6Ii8yNjExMTg0Mi8zMzczNDQwNDktZWNjN2ZlNzQtODIyNC00ODdlLTk2NzMtMmE2NmNiYThjOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE2MTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOTIyN2RiNTRiNTlkZTNjZDc1Zjg2YTAyZDEwODVlZDNlYWNlOGQ5MzhiMGIxNzZlYzM2MmE0NTYyMTFiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KgjUNZwleIvEJP6jsK4pVjL1MZ8fHm9EIpoZMP1LwGI"> Also it puts content of the file in to the terminal during the build

Try to use ```//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs``` this instead of new URL method. That helped me.

**Comment by nike1v** [comment]
I have discovered that this issue persist only in case when component with pdfjs-dist or react-pdf have "use client" directive or any parent component have this. If whole chain is server components, than it works fine. Probably I should open an issue for PDF.JS itsef, because it looks like their problem.

**Comment by nike1v** [comment]
Weird that I already provided the workerSrc at the most top page.tsx which is server component and even now my PDFViewer component throws this error when used with Turbopack. Probably this is why you suggested to set workerSrc only in client components.

**Comment by wojtekmaj** [comment]
- If you're using Turbo and see "Module not found" or "Failed to compile": Please kindly share your feedback with Next.js team and in the meantime try default Webpack mode instead.
- If you're not using Turbo and see "Module not found", ensure you don't have several copies of pdfjs-dist installed, remove node_modules and install your repo from scratch. 
- If you see "'import', and 'export' cannot be used outside of module code":  Please kindly share your feedback on using ESM workers with Next.js team and in the meantime try setting `swcMinify: false`.

**Comment by titouancreach** [comment]
> > > Ok, so remove node_modules clean yarn.lock file yarn install Works with 9.0.0, but before I did the same and didn't worked. I don't know ...
> > 
> > 
> > As you said, probably some cache issues, glad it worked.
> 
> The build failing in GitHub Action and locally now, but next dev works Creating an optimized production build ... Failed to compile.
> 
> ```
> static/media/pdf.worker.min.9b170941.mjs from Terser
>   x 'import', and 'export' cannot be used outside of module code
>     ,-[18:1]
>  18 |  *
>  19 |  * @licend The above is the entire license notice for the
>  20 |  * JavaScript code in this page
> ```
> 
> <img alt="image" width="1495" src="https://private-user-images.githubusercontent.com/26111842/337344049-ecc7fe74-8224-487e-9673-2a66cba8c96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTUyNTQsIm5iZiI6MTcxODYxNDk1NCwicGF0aCI6Ii8yNjExMTg0Mi8zMzczNDQwNDktZWNjN2ZlNzQtODIyNC00ODdlLTk2NzMtMmE2NmNiYThjOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5MDIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZmEzMDYxNGJkOTc1YzVlMDY0OTBhNDI1NjJmNWUwODVjY2FiZWU2NWQ3NzIwNWIwNDM4YTFiNjE1NGI4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vWaT5TcJ167GffsHUDvgHtnN3TajlnCdsjTNI0N2gHc"> Also it puts content of the file in to the terminal during the build

Hello, it's confirmed for me too :

I can see this message using `next build` with react pdf 9.0.0 (8.x was working)

```
static/media/pdf.worker.min.9b170941.mjs from Terser
  x 'import', and 'export' cannot be used outside of module code
    ,-[18:1]
 18 |  *
 19 |  * @licend The above is the entire license notice for the
 20 |  * JavaScript code in this page
 21 |  */var e={d:(t,i)=>{for(var a in i)e.o(i,a)&&!e.o(t,a)&&Object.defineProperty(t,a,{enumerable:!0,get:i[a]})},o:(e,t)=>Object.prototype.hasOwnProperty.call(e,t)},__webpack_exports__=globalThis.pdfjsWorker={};e.d(__webpack_exports__,{WorkerMessageHandler:()=>W
```

This snippet show that webpack is used (turbo pack in dev is working), Terser is used (and not swc minifier)

**Comment by wojtekmaj** [comment]
@titouancreach This has been recently fixed in https://github.com/vercel/next.js/pull/66817 and is waiting for the next release. In the meantime try setting swcMinify: false.

The "from Terser" is another Next.js bug, it's NOT coming from Terser.

Here's the exact line in SWC where it's coming from :) 

https://github.com/swc-project/swc/blob/ae6ab656fa0cbf2a5cde0523f8282a7eb61a7245/crates/swc_ecma_parser/src/error.rs#L416

**Comment by titouancreach** [comment]
@wojtekmaj ohhhh, thanks for clarification !

**Comment by ArnoSoontjens** [comment]
We're also seeing
```
static/media/pdf.worker.min.9b170941.mjs from Terser
  x 'import', and 'export' cannot be used outside of module code
    ,-[18:1]
 18 |  *
 19 |  * @licend The above is the entire license notice for the
 20 |  * JavaScript code in this page
```
For us, setting `swcMinify: false` didn't work, the error persisted (during build, not in development). 
The build did start working however, when using the worker from CDN (and without `swcMinify: false`) , like this:
```
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
```

**Comment by jamesryan-dev** [comment]
+1 experiencing this issue

**Comment by Harshpandey9156** [comment]
![image](https://github.com/user-attachments/assets/3119c3f2-2446-463b-a152-014729447eff)


anyone can help me in this i an facing this issue in redering the pdf and i have use react-pdf

**Comment by jamesryan-dev** [comment]
would need to see code @Harshpandey9156 - probably best to ask on Stack Overflow

**Comment by Armedips** [comment]
![web service](https://github.com/user-attachments/assets/e39e1a25-0a19-4d59-8bec-2d695814ace7)

anyone have the same problem? ..can anyone explain?
im use pdfjs and pdf-viewer to display the pdf in frontend side

**Comment by GloriaBargoria** [comment]
I am getting the same issue. Did you get a solution the the issue? 

> ![web service](https://private-user-images.githubusercontent.com/175378807/365506005-e39e1a25-0a19-4d59-8bec-2d695814ace7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTIyODMsIm5iZiI6MTcyNjQ5MTk4MywicGF0aCI6Ii8xNzUzNzg4MDcvMzY1NTA2MDA1LWUzOWUxYTI1LTBhMTktNGQ1OS04YmVjLTJkNjk1ODE0YWNlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxMzA2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzU4NGUxOTVjNjllZTU0MmEwMzQ5NWFhMWIyOGFmZDNiOGM2Zjk4ZDZjMTNhNTJiOTZjMjhhM2UwZmU4YmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a8zeE_YQg9MZKT9ao-1JBbGYrBe-vhMP4mn5AAd6cYU)
> 
> anyone have the same problem? ..can anyone explain? im use pdfjs and pdf-viewer to display the pdf in frontend side

**Comment by Bumboobee** [comment]
> > > > Ok, so remove node_modules clean yarn.lock file yarn install Works with 9.0.0, but before I did the same and didn't worked. I don't know ...
> > > 
> > > 
> > > As you said, probably some cache issues, glad it worked.
> > 
> > 
> > The build failing in GitHub Action and locally now, but next dev works Creating an optimized production build ... Failed to compile.
> > ```
> > static/media/pdf.worker.min.9b170941.mjs from Terser
> >   x 'import', and 'export' cannot be used outside of module code
> >     ,-[18:1]
> >  18 |  *
> >  19 |  * @licend The above is the entire license notice for the
> >  20 |  * JavaScript code in this page
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="1495" src="https://private-user-images.githubusercontent.com/26111842/337344049-ecc7fe74-8224-487e-9673-2a66cba8c96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTA1NDQsIm5iZiI6MTcxNzY5MDI0NCwicGF0aCI6Ii8yNjExMTg0Mi8zMzczNDQwNDktZWNjN2ZlNzQtODIyNC00ODdlLTk2NzMtMmE2NmNiYThjOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE2MTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOTIyN2RiNTRiNTlkZTNjZDc1Zjg2YTAyZDEwODVlZDNlYWNlOGQ5MzhiMGIxNzZlYzM2MmE0NTYyMTFiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KgjUNZwleIvEJP6jsK4pVjL1MZ8fHm9EIpoZMP1LwGI"> Also it puts content of the file in to the terminal during the build
> 
> Try to use `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs` this instead of new URL method. That helped me.

This works for me. Thanks a lot!!

**Comment by grundmanise** [comment]
We managed to resolve these issues by memoizing non-primitive props using useMemo, useRef, or useCallback. Hope this helps someone
